version: '3.9'
services:
  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: autodb
    ports:
      - 5432:5432