version: '3.9'
services:
  redis:
    image: redis:7.0.2-alpine
    restart: always
    ports:
      - '6379:6379'

  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: autodb
    ports:
      - "5432:5432"